shamefullyHoist: true
strictPeerDependencies: false

packages:
  - .

ignoredBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - esbuild
  - sharp
  - unrs-resolver
  - vue-demi
  - workerd
